name: automerge-release-please
on:
  pull_request:
    types: [labeled, synchronize, reopened, ready_for_review]

permissions:
  contents: write
  pull-requests: write

jobs:
  enable-automerge:
    if: >-
      github.event.pull_request.user.login == 'github-actions[bot]' &&
      contains(join(github.event.pull_request.labels.*.name, ','), 'autorelease: pending')
    runs-on: ubuntu-latest
    steps:
      - name: Enable PR auto-merge (squash)
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
